version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:30"
      timezone: "Asia/Hong_Kong"
    open-pull-requests-limit: 10
    target-branch: main
