name: Combine Dependabot PRs

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - name: combine-prs
        id: combine-prs
        uses: crypto-billy/gha-combine-prs@v1.6.0
        with:
          pr_title: Combined Dependabot PRs
          select_label: dependencies
          labels: dependencies,combined-pr
          github_token: ${{ secrets.PAT }}
          ci_required: "false"
          review_required: "false"
